---
- hosts: sql_server
  become: true

  tasks:
    - name: Print OS info
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Install Apache
      ansible.builtin.package:
        name: apache2
        state: present
